const EVENT_KEYS = {

  ON_LANDING_PAGE_VISIT : "ON_LANDING_PAGE_VISIT",
  ON_RESERVE_YOUR_SEAT_CLICK : "ON_RESERVE_YOUR_SEAT_CLICK",
  ON_SCROLL : "ON_SCROLL",

  ON_REGISTER_PAGE_OPEN: "ON_REGISTER_PAGE_OPEN",
  ON_BASIC_INFO_NEXT: "ON_BASIC_INFO_NEXT",
  ON_QUESTIONAIRE_SHOW: "ON_QUESTIONAIRE_SHOW",
  ON_QUESTIONAIRE_NEXT: "ON_QUESTIONAIRE_NEXT",
  ON_PAYMENT_SHOW: "ON_PAYMENT_SHOW",
  ON_CONFIRM_MY_SEAT: "ON_CONFIRM_MY_SEAT",
};


export {
    EVENT_KEYS
}