import type { Metadata } from "next";
import local from "next/font/local";
import "aos/dist/aos.css";

import AOSProvider from "./dark-version/component/AOSProvider";
import "./globals.css";

const geistSans = local({
  src: [
    {
      path: "../public/font/Prompt/Prompt-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-geist-sans",
});

const geistMono = local({
  src: [
    {
      path: "../public/font/Prompt/Prompt-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-geist-mono",
});

const promt = local({
  src: [
    {
      path: "../public/font/Prompt/Prompt-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-prompt",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${promt.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AOSProvider />
        {children}
      </body>
    </html>
  );
}
